server:
  port: 2121
logging:
  file: SSN-APP-LOGS.log
  level:
    root: INFO
    com.usa.gov.ssn: DEBUG
    
 #Spring 
spring:
  #database configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true   
        dialect:  org.hibernate.dialect.MySQL5Dialect       #org.hibernate.dialect.MySQL5Dialectorg.hibernate.dialect.Oracle10gDialect 
  datasource:
#    username: system
#    password: pulla143
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:mysql://localhost:3306/sodam
    username: root
    password: pULLA143
    driver-class-name: com.mysql.jdbc.Driver